Python/Prac7/Python/myproject/myapp1/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
      
    path('', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('next/', views.next, name='next'),
]

Python/Prac7/Python/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from myapp1 import views
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('myapp1.urls')), 
]

Python/Prac7/Python/myproject/myapp1/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.hashers import make_password
from django.db import models
from django.contrib.auth.hashers import check_password 

class User(models.Model):
    username = models.CharField(max_length=30, unique=True)
    passw = models.CharField(max_length=128, blank=True, null=True)  
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    last_login = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username

    def set_password(self, raw_password):
        self.passw = make_password(raw_password)

    @classmethod 
    def authenticate(cls, username, passw):
        try:
            user = cls.objects.get(username=username)
            print(f"Provided password: {passw}")
            print(f"Stored hashed password: {user.passw}")
            # if check_password(password, user.passw):
            if user.passw == passw:
                print("auth success")
                return user
        except cls.DoesNotExist:
            return None
        return None

Python/Prac7/Python/myproject/myapp1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import User
from django.contrib.auth import authenticate, login
 

def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                return render(request, 'sign_up.html', {'error': 'Username is already taken'})
            
            user = User.objects.create(username=username, first_name=first_name, last_name=last_name, passw=password1)
            # user.set_password(password1)
            # user.save()
            
            return redirect('login')
        else:
            return render(request, 'sign_up.html', {'error': 'Passwords do not match'}) 
    
    return render(request, 'sign_up.html')
 

def user_login(request):
    if request.method == 'POST':
        context = {}
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.authenticate(username=username, passw=password)

        if user is not None:
            login(request, user)
            return redirect('next')
        else:
            context.update({'loginerror':"invalid credentials"})
            print(context)
            return render(request, 'login.html', context=context)
    
    return render(request, 'login.html')

def next(request):
    return render(request, 'next.html')

Python/Prac7/Python/myproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>Login</title> 
</head>

<body>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-6">
                <h2 class="text-center">Login</h2>
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Username:</label>
                        <input type="text" class="form-control" id="id_username" name="username" required>
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        <input type="password" class="form-control" id="id_password" name="password" required>
                    </div> 
                    <div>
                        {{ loginerror }}
                    </div> 
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                </form>
            </div>
        </div>
    </div>    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

</html>

Python/Prac7/Python/myproject/templates/next.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>Welcome Home</title> 
</head>

<body>
    <div class="container">
        <div class="row justify-content-center align-items-center" style="background-color: bisque; height: 100vh;">
            <div class="col-sm-6 text-center">
                <div class="welcome-message" style="background-color: rgb(230, 216, 198); padding: 20px;">
                    <h1>Welcome {{ user.username }}</h1>
                    <p>You are successfully logged in. Welcome to the home page!</p>
                </div>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</body>

</html>

Python/Prac7/Python/myproject/templates/sign_up.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>Sign Up</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center pt-5 align-items-center">
            <hr style="width:35vw">
            <h2 class="text-center">Sign Up</h2>
            <hr style="width: 35vw;">
            <div></div>
            <form action="{% url 'signup' %}" method="post" class="needs-validation col-sm-6 pt-4 align-self-center" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    <input type="text" class="form-control" id="id_username" name="username" required>
                    <div class="invalid-feedback">Please enter a username.</div>
                </div>
                <div class="form-group">
                    <label for="id_first_name">First Name:</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name" required>
                    <div class="invalid-feedback">Please enter your first name.</div>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name:</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" required>
                    <div class="invalid-feedback">Please enter your last name.</div>
                </div>
                <div class="form-group">
                    <label for="id_password1">Password:</label>
                    <input type="password" class="form-control" id="id_password1" name="password1" required>
                    <div class="invalid-feedback">Please enter a password.</div>
                </div>
                <div class="form-group">
                    <label for="id_password2">Confirm Password:</label>
                    <input type="password" class="form-control" id="id_password2" name="password2" required>
                    <div class="invalid-feedback">Please confirm your password.</div>
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
        </div>        
    </div>  
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

</html>